SELECT
	MAX(len0),
	MAX(len1),
	MAX(len2),
	MAX(len3),
	MAX(program_start_time),
	MAX(program_time),
	MAX(progmra_end_time),
	MAX(len4),
	MAX(len5),
	MAX(len6),
	MAX(len7),
	MAX(len8),
	MAX(len9),
	MAX(len10),
	MAX(len11),
	MIN(len0),
	MIN(len1),
	MIN(len2),
	MIN(len3),
	MIN(program_start_time),
	MIN(program_time),
	MIN(progmra_end_time),
	MIN(len4),
	MIN(len5),
	MIN(len6),
	MIN(len7),
	MIN(len8),
	MIN(len9),
	MIN(len10),
	MIN(len11),
	COUNT(DISTINCT(station_code)),
	COUNT(DISTINCT(program_code)),
	COUNT(DISTINCT(program_day_week)),
	COUNT(DISTINCT(program_date)),
	COUNT(DISTINCT(program_start_time)),
	COUNT(DISTINCT(program_time)),
	COUNT(DISTINCT(progmra_end_time)),
	COUNT(DISTINCT(ban_code1)),
	COUNT(DISTINCT(ban_code2)),
	COUNT(DISTINCT(ban_code3)),
	COUNT(DISTINCT(sin_toku)),
	COUNT(DISTINCT(br_format)),
	COUNT(DISTINCT(final_code)),
	COUNT(DISTINCT(program_name)),
	COUNT(DISTINCT(program_name_kana)),
	SUM(CASE WHEN station_code  IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_code IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_day_week IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_date IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_start_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN progmra_end_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code1 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code2 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code3 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN sin_toku IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN br_format IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN final_code IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name_kana IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN station_code='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_code='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_day_week='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_date='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code1='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code2='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code3='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN sin_toku='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN br_format='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN final_code='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name='' THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name_kana='' THEN 1 ELSE 0 END)
FROM
	(
    -- 文字列を長さに変換する仮テーブル
    SELECT
        *,
		    char_length(station_code) AS len0,
		    char_length(program_code) AS len1,
		    char_length(program_day_week) AS len2,
		    char_length(program_date) AS len3,
		    char_length(ban_code1) AS len4,
		    char_length(ban_code2) AS len5,
		    char_length(ban_code3) AS len6,
		    char_length(sin_toku) AS len7,
			char_length(br_format) AS len8,
			char_length(final_code) AS len9,
			char_length(program_name) AS len10,
			char_length(program_name_kana) AS len11
    FROM
        original.tv_program
    ) AS length_table;
			   
			   
SELECT
	MAX(station_code),
	MAX(len0),
	MAX(program_day_week),
	MAX(program_date),
	MAX(program_start_time),
	MAX(program_time),
	MAX(program_end_time),
	MAX(ban_code1),
	MAX(ban_code2),
	MAX(len1),
	MAX(len4),
	MAX(br_format),
	MAX(final_code),
	MAX(len2),
	MAX(len3),
	MIN(station_code),
	MIN(len0),
	MIN(program_day_week),
	MIN(program_date),
	MIN(program_start_time),
	MIN(program_time),
	MIN(program_end_time),
	MIN(ban_code1),
	MIN(ban_code2),
	MIN(len1),
	MIN(len4),
	MIN(br_format),
	MIN(final_code),
	MIN(len2),
	MIN(len3),
	COUNT(DISTINCT(station_code)),
	COUNT(DISTINCT(program_code)),
	COUNT(DISTINCT(program_day_week)),
	COUNT(DISTINCT(program_date)),
	COUNT(DISTINCT(program_start_time)),
	COUNT(DISTINCT(program_time)),
	COUNT(DISTINCT(program_end_time)),
	COUNT(DISTINCT(ban_code1)),
	COUNT(DISTINCT(ban_code2)),
	COUNT(DISTINCT(ban_code3)),
	COUNT(DISTINCT(sin_toku)),
	COUNT(DISTINCT(br_format)),
	COUNT(DISTINCT(final_code)),
	COUNT(DISTINCT(program_name)),
	COUNT(DISTINCT(program_name_kana)),
	SUM(CASE WHEN station_code IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_code IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_day_week IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_date IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_start_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_end_time IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code1 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code2 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN ban_code3 IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN sin_toku IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN br_format IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN final_code IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name IS NULL THEN 1 ELSE 0 END),
	SUM(CASE WHEN program_name_kana IS NULL THEN 1 ELSE 0 END)
FROM
	(
    -- 文字列を長さに変換する仮テーブル
    SELECT
        *,
		    char_length(program_code) AS len0,
		    char_length(ban_code3) AS len1,
			char_length(program_name) AS len2,
			char_length(program_name_kana) AS len3,
			char_length(sin_toku) AS len4
    FROM
        processed.tv_program
    ) AS length_table;