SELECT
  MIN(LENGTH(br_date)),
  MIN(LENGTH(br_day_week)),
  MIN(LENGTH(house_num)),
  MIN(LENGTH(ind_num)),
  MIN(start_time),
  MIN(end_time),
  MIN(LENGTH(station_code)),
  MIN(LENGTH(tv_num)),
  MIN(LENGTH(data_agg_type)),
  MIN(LENGTH(dataseq)),
  
  MAX(LENGTH(br_date)),
  MAX(LENGTH(br_day_week)),
  MAX(LENGTH(house_num)),
  MAX(LENGTH(ind_num)),
  MAX(start_time),
  MAX(end_time),
  MAX(LENGTH(station_code)),
  MAX(LENGTH(tv_num)),
  MAX(LENGTH(data_agg_type)),
  MAX(LENGTH(dataseq)),
  
  COUNT(DISTINCT(br_date)),
  COUNT(DISTINCT(br_day_week)),
  COUNT(DISTINCT(house_num)),
  COUNT(DISTINCT(ind_num)),
  COUNT(DISTINCT(start_time)),
  COUNT(DISTINCT(end_time)),
  COUNT(DISTINCT(station_code)),
  COUNT(DISTINCT(tv_num)),
  COUNT(DISTINCT(data_agg_type)),
  COUNT(DISTINCT(dataseq)),
  
  SUM( CASE WHEN br_date IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN br_day_week IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN house_num IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN ind_num IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN start_time IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN end_time IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN station_code IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN tv_num IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN data_agg_type IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN dataseq IS NULL THEN 1 ELSE 0 END),
  
  SUM( CASE WHEN br_date =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN br_day_week =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN house_num =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN ind_num =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN station_code =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN tv_num =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN data_agg_type =  '' THEN 1 ELSE 0 END),
  SUM( CASE WHEN dataseq =  '' THEN 1 ELSE 0 END)
FROM
  original.tv_orgn_p_cv;
  
-- processed
SELECT
  MIN(br_start_datetime),
  MIN(br_end_datetime),
  MIN(br_day_week),
  MIN(house_num),
  MIN(station_code),
  MIN(tv_num),
  MIN(data_agg_type),
  MIN(dataseq),
  MIN(br_date),
  
  MAX(br_start_datetime),
  MAX(br_end_datetime),
  MAX(br_day_week),
  MAX(house_num),
  MAX(station_code),
  MAX(tv_num),
  MAX(data_agg_type),
  MAX(dataseq),
  MAX(br_date),
  
  COUNT(DISTINCT(br_start_datetime)),
  COUNT(DISTINCT(br_end_datetime)),
  COUNT(DISTINCT(br_day_week)),
  COUNT(DISTINCT(house_num)),
  COUNT(DISTINCT(station_code)),
  COUNT(DISTINCT(tv_num)),
  COUNT(DISTINCT(data_agg_type)),
  COUNT(DISTINCT(dataseq)),
  COUNT(DISTINCT(br_date)),
  
  SUM( CASE WHEN br_start_datetime IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN br_end_datetime IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN br_day_week IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN house_num IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN station_code IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN tv_num IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN data_agg_type IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN dataseq IS NULL THEN 1 ELSE 0 END),
  SUM( CASE WHEN br_date IS NULL THEN 1 ELSE 0 END)
FROM
  processed.tv_orgn_p_cv;
  
